// Code generated by protoc-gen-go.
// source: wallet.proto
// DO NOT EDIT!

/*
Package wallet is a generated protocol buffer package.

It is generated from these files:
	wallet.proto

It has these top-level messages:
	Total
	Operation
*/
package wallet

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Total struct {
	Value int64 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *Total) Reset()                    { *m = Total{} }
func (m *Total) String() string            { return proto.CompactTextString(m) }
func (*Total) ProtoMessage()               {}
func (*Total) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Operation struct {
	Value int64                       `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	Note  string                      `protobuf:"bytes,2,opt,name=note" json:"note,omitempty"`
	Time  *google_protobuf1.Timestamp `protobuf:"bytes,3,opt,name=time" json:"time,omitempty"`
}

func (m *Operation) Reset()                    { *m = Operation{} }
func (m *Operation) String() string            { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()               {}
func (*Operation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Operation) GetTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func init() {
	proto.RegisterType((*Total)(nil), "wallet.Total")
	proto.RegisterType((*Operation)(nil), "wallet.Operation")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Wallet service

type WalletClient interface {
	GetTotal(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*Total, error)
	AddOperation(ctx context.Context, in *Operation, opts ...grpc.CallOption) (*Total, error)
}

type walletClient struct {
	cc *grpc.ClientConn
}

func NewWalletClient(cc *grpc.ClientConn) WalletClient {
	return &walletClient{cc}
}

func (c *walletClient) GetTotal(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*Total, error) {
	out := new(Total)
	err := grpc.Invoke(ctx, "/wallet.Wallet/GetTotal", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) AddOperation(ctx context.Context, in *Operation, opts ...grpc.CallOption) (*Total, error) {
	out := new(Total)
	err := grpc.Invoke(ctx, "/wallet.Wallet/AddOperation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Wallet service

type WalletServer interface {
	GetTotal(context.Context, *google_protobuf.Empty) (*Total, error)
	AddOperation(context.Context, *Operation) (*Total, error)
}

func RegisterWalletServer(s *grpc.Server, srv WalletServer) {
	s.RegisterService(&_Wallet_serviceDesc, srv)
}

func _Wallet_GetTotal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).GetTotal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.Wallet/GetTotal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).GetTotal(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_AddOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Operation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).AddOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.Wallet/AddOperation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).AddOperation(ctx, req.(*Operation))
	}
	return interceptor(ctx, in, info, handler)
}

var _Wallet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wallet.Wallet",
	HandlerType: (*WalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTotal",
			Handler:    _Wallet_GetTotal_Handler,
		},
		{
			MethodName: "AddOperation",
			Handler:    _Wallet_AddOperation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("wallet.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4f, 0xcc, 0xc9,
	0x49, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0xa4, 0xa4, 0xd3, 0xf3,
	0xf3, 0xd3, 0x73, 0x52, 0xf5, 0xc1, 0xa2, 0x49, 0xa5, 0x69, 0xfa, 0xa9, 0xb9, 0x05, 0x25, 0x95,
	0x10, 0x45, 0x52, 0xf2, 0xe8, 0x92, 0x25, 0x99, 0xb9, 0xa9, 0xc5, 0x25, 0x89, 0xb9, 0x05, 0x10,
	0x05, 0x4a, 0xb2, 0x5c, 0xac, 0x21, 0xf9, 0x25, 0x89, 0x39, 0x42, 0x22, 0x5c, 0xac, 0x65, 0x89,
	0x39, 0xa5, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x10, 0x8e, 0x52, 0x2a, 0x17, 0xa7,
	0x7f, 0x41, 0x6a, 0x51, 0x62, 0x49, 0x66, 0x7e, 0x1e, 0x76, 0x25, 0x42, 0x42, 0x5c, 0x2c, 0x79,
	0xf9, 0x25, 0xa9, 0x12, 0x4c, 0x40, 0x41, 0xce, 0x20, 0x30, 0x5b, 0x48, 0x8f, 0x8b, 0x05, 0x64,
	0x91, 0x04, 0x33, 0x50, 0x8c, 0xdb, 0x48, 0x4a, 0x0f, 0xe2, 0x0a, 0x3d, 0x98, 0x2b, 0xf4, 0x42,
	0x60, 0xae, 0x08, 0x02, 0xab, 0x33, 0x2a, 0xe4, 0x62, 0x0b, 0x07, 0xfb, 0x46, 0xc8, 0x98, 0x8b,
	0xc3, 0x3d, 0xb5, 0x04, 0xe2, 0x24, 0x31, 0x0c, 0x7d, 0xae, 0x20, 0xaf, 0x49, 0xf1, 0xea, 0x41,
	0x03, 0x02, 0xac, 0x4c, 0x89, 0x41, 0xc8, 0x88, 0x8b, 0xc7, 0x31, 0x25, 0x05, 0xe1, 0x50, 0x41,
	0x98, 0x02, 0xb8, 0x10, 0x86, 0x9e, 0x24, 0x36, 0xb0, 0xa1, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xf2, 0xef, 0x60, 0x43, 0x55, 0x01, 0x00, 0x00,
}
