// Code generated by protoc-gen-go.
// source: wallet/wallet.proto
// DO NOT EDIT!

/*
Package wallet is a generated protocol buffer package.

It is generated from these files:
	wallet/wallet.proto

It has these top-level messages:
	Total
*/
package wallet

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Total struct {
	Value            *int64 `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Total) Reset()                    { *m = Total{} }
func (m *Total) String() string            { return proto.CompactTextString(m) }
func (*Total) ProtoMessage()               {}
func (*Total) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Total) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*Total)(nil), "wallet.Total")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Wallet service

type WalletClient interface {
	GetTotal(ctx context.Context, in *Total, opts ...grpc.CallOption) (*Total, error)
}

type walletClient struct {
	cc *grpc.ClientConn
}

func NewWalletClient(cc *grpc.ClientConn) WalletClient {
	return &walletClient{cc}
}

func (c *walletClient) GetTotal(ctx context.Context, in *Total, opts ...grpc.CallOption) (*Total, error) {
	out := new(Total)
	err := grpc.Invoke(ctx, "/wallet.Wallet/GetTotal", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Wallet service

type WalletServer interface {
	GetTotal(context.Context, *Total) (*Total, error)
}

func RegisterWalletServer(s *grpc.Server, srv WalletServer) {
	s.RegisterService(&_Wallet_serviceDesc, srv)
}

func _Wallet_GetTotal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Total)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).GetTotal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.Wallet/GetTotal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).GetTotal(ctx, req.(*Total))
	}
	return interceptor(ctx, in, info, handler)
}

var _Wallet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wallet.Wallet",
	HandlerType: (*WalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTotal",
			Handler:    _Wallet_GetTotal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("wallet/wallet.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 94 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x4f, 0xcc, 0xc9,
	0x49, 0x2d, 0xd1, 0x87, 0x50, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x10, 0x9e, 0x92,
	0x18, 0x17, 0x6b, 0x48, 0x7e, 0x49, 0x62, 0x8e, 0x10, 0x2f, 0x17, 0x6b, 0x59, 0x62, 0x4e, 0x69,
	0xaa, 0x04, 0xa3, 0x02, 0x93, 0x06, 0xb3, 0x91, 0x09, 0x17, 0x5b, 0x38, 0x58, 0x85, 0x90, 0x16,
	0x17, 0x87, 0x7b, 0x6a, 0x09, 0x54, 0x91, 0x1e, 0xd4, 0x10, 0x30, 0x57, 0x0a, 0x95, 0xab, 0xc4,
	0x00, 0x08, 0x00, 0x00, 0xff, 0xff, 0x7b, 0xe7, 0x41, 0x99, 0x6b, 0x00, 0x00, 0x00,
}
